# Generated by Django 4.2 on 2023-06-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="New Quiz", max_length=255, verbose_name="Quiz Title"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quiz.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Slogan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("question", models.CharField(max_length=255, verbose_name="TagLine")),
                (
                    "date_created",
                    models.DateTimeField(auto_now=True, verbose_name="Date Created"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active Status"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="slogan",
                        to="quiz.quizzes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slogan",
                "verbose_name_plural": "Slogans",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "brand_text",
                    models.CharField(max_length=255, verbose_name="Brand Text"),
                ),
                ("is_right", models.BooleanField(default=False)),
                (
                    "slogan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="brand",
                        to="quiz.slogan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["id"],
            },
        ),
    ]
