# Generated by Django 4.2 on 2023-06-23 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterField(
            model_name="quizzes",
            name="category",
            field=models.ForeignKey(
                default="Generic",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="quiz.category",
            ),
        ),
    ]
